name: build tar

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
#      - name: Setup JDK
#        uses: actions/setup-java@v4
#        with:
#          distribution: adopt
#          java-version: 11
      - name: Setup JDK
        run: |
          sudo apt install -y openjdk-11-jdk
          jdk_path=$(update-java-alternatives --list | grep "java-1.11." |awk '{print $3}')
          sudo update-java-alternatives --set ${jdk_path}
          export JAVA_HOME=${jdk_path}
          echo "JAVA_HOME=${jdk_path}" >> $GITHUB_ENV
          echo "JAVA_HOME=${JAVA_HOME}"
          java -version
      - uses: cedx/setup-ant@v4
        with:
          optional-tasks: false
          version: ">=1.10.0"
      - name: build
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          ant jar
          ant bintar
      - name: "Upload files"
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          path: ${{ github.workspace }}/build/apache-cassandra-.*.tar.gz
          name: apache-cassandra
