name: build tar

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
#      - name: Setup JDK
#        uses: actions/setup-java@v4
#        with:
#          distribution: adopt
#          java-version: 11
      - name: Setup JDK
        run: |
          sudo apt install -y openjdk-11-jdk
          sudo update-java-alternatives --set /usr/lib/jvm/java-1.11.0-openjdk-amd64
      - uses: cedx/setup-ant@v4
        with:
          optional-tasks: true
          version: ">=1.10.0"
      - name: build
        run: |
          ant jar
          ant bintar
      - name: "Upload files"
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          path: ${{ github.workspace }}/build/apache-cassandra-.*.tar.gz
          name: apache-cassandra
